In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
import glob
import os
from datetime import datetime as dt
from pandas.tseries.offsets import *

In [ ]:
path = "/content/drive/MyDrive/CBRE"
all_files = glob.glob(path+"/*.csv")

full_data = []
for file in all_files:
    cbre_df = pd.read_csv(file, header = 0, index_col = None)
    full_data.append(cbre_df)

cbre_df2 = pd.concat(full_data, axis= 0, ignore_index= None, sort = False)

In [ ]:
cbre_df2.head()

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin
0,DZD,127.8460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARS,74.1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AUD,1.3559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AZN,1.6988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BHD,0.3770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(cbre_df2.shape)

(25035, 12)

In [ ]:
cbre_df2 = cbre_df2.drop_duplicates()
cbre_df2

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin
0,DZD,127.8460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARS,74.1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AUD,1.3559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AZN,1.6988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BHD,0.3770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
24944,EUR,NaN,18419.0,0.0,4P4,111999.0,220101.0,553.24,27/01/2020,27/01/2020,13.0,ONL
24945,EUR,NaN,18168.0,0.0,4P4,111999.0,220101.0,3485.98,27/01/2020,27/01/2020,13.0,ONL
24946,EUR,NaN,18564.0,0.0,4P4,111999.0,220101.0,585.63,27/01/2020,27/01/2020,13.0,ONL
24947,EUR,NaN,18499.0,0.0,4P4,111999.0,220101.0,333.25,27/01/2020,27/01/2020,14.0,ONL
24948,EUR,NaN,18478.0,0.0,4P4,111999.0,220105.0,55838.90,27/01/2020,27/01/2020,15.0,ONL

In [ ]:
cbre_df2.isnull()

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin
0,False,False,True,True,True,True,True,True,True,True,True,True
1,False,False,True,True,True,True,True,True,True,True,True,True
2,False,False,True,True,True,True,True,True,True,True,True,True
3,False,False,True,True,True,True,True,True,True,True,True,True
4,False,False,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
24944,False,True,False,False,False,False,False,False,False,False,False,False
24945,False,True,False,False,False,False,False,False,False,False,False,False
24946,False,True,False,False,False,False,False,False,False,False,False,False
24947,False,True,False,False,False,False,False,False,False,False,False,False
24948,False,True,False,False,False,False,False,False,False,False,False,False

In [ ]:
cbre_df2 = cbre_df2.replace(to_replace = np.nan, value = 1337)
cbre_df2

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin
0,DZD,127.8460,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1337,1337,1337.0,1337
1,ARS,74.1750,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1337,1337,1337.0,1337
2,AUD,1.3559,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1337,1337,1337.0,1337
3,AZN,1.6988,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1337,1337,1337.0,1337
4,BHD,0.3770,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1337,1337,1337.0,1337
...,...,...,...,...,...,...,...,...,...,...,...,...
24944,EUR,1337.0000,18419.0,0.0,4P4,111999.0,220101.0,553.24,27/01/2020,27/01/2020,13.0,ONL
24945,EUR,1337.0000,18168.0,0.0,4P4,111999.0,220101.0,3485.98,27/01/2020,27/01/2020,13.0,ONL
24946,EUR,1337.0000,18564.0,0.0,4P4,111999.0,220101.0,585.63,27/01/2020,27/01/2020,13.0,ONL
24947,EUR,1337.0000,18499.0,0.0,4P4,111999.0,220101.0,333.25,27/01/2020,27/01/2020,14.0,ONL
24948,EUR,1337.0000,18478.0,0.0,4P4,111999.0,220105.0,55838.90,27/01/2020,27/01/2020,15.0,ONL

In [ ]:
cbre_df2.isnull()

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
24944,False,False,False,False,False,False,False,False,False,False,False,False
24945,False,False,False,False,False,False,False,False,False,False,False,False
24946,False,False,False,False,False,False,False,False,False,False,False,False
24947,False,False,False,False,False,False,False,False,False,False,False,False
24948,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
cbre_df2["Acctg Date"] = pd.to_datetime(cbre_df2["Acctg Date"])
cbre_df2["Date"] = pd.to_datetime(cbre_df2["Date"])
cbre_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24599 entries, 0 to 24948
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Currency    24599 non-null  object
 1   Per USD     24599 non-null  float64
 2   Voucher     24599 non-null  float64
 3   Seq         24599 non-null  float64
 4   Type        24599 non-null  object
 5   Account     24599 non-null  float64
 6   Func Unit   24599 non-null  float64
 7   Amount      24599 non-null  float64
 8   Acctg Date  24599 non-null  datetime64[ns]
 9   Date        24599 non-null  datetime64[ns]
 10  Line #      24599 non-null  float64
 11  Origin      24599 non-null  object
dtypes: datetime64[ns](2), float64(7), object(3)
memory usage: 2.4+ MB

<ipython-input-71-0195264208c2>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  cbre_df2["Acctg Date"] = pd.to_datetime(cbre_df2["Acctg Date"])
<ipython-input-71-0195264208c2>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  cbre_df2["Date"] = pd.to_datetime(cbre_df2["Date"])

In [ ]:
cbre_df2['no_of_diff'] = (cbre_df2['Acctg Date']-cbre_df2["Date"]).dt.days
cbre_df2

,Currency,Per USD,Voucher,Seq,Type,Account,Func Unit,Amount,Acctg Date,Date,Line #,Origin,no_of_diff
0,DZD,127.8460,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1970-01-01 00:00:00.000001337,1970-01-01 00:00:00.000001337,1337.0,1337,0
1,ARS,74.1750,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1970-01-01 00:00:00.000001337,1970-01-01 00:00:00.000001337,1337.0,1337,0
2,AUD,1.3559,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1970-01-01 00:00:00.000001337,1970-01-01 00:00:00.000001337,1337.0,1337,0
3,AZN,1.6988,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1970-01-01 00:00:00.000001337,1970-01-01 00:00:00.000001337,1337.0,1337,0
4,BHD,0.3770,1337.0,1337.0,1337,1337.0,1337.0,1337.00,1970-01-01 00:00:00.000001337,1970-01-01 00:00:00.000001337,1337.0,1337,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24944,EUR,1337.0000,18419.0,0.0,4P4,111999.0,220101.0,553.24,2020-01-27 00:00:00.000000000,2020-01-27 00:00:00.000000000,13.0,ONL,0
24945,EUR,1337.0000,18168.0,0.0,4P4,111999.0,220101.0,3485.98,2020-01-27 00:00:00.000000000,2020-01-27 00:00:00.000000000,13.0,ONL,0
24946,EUR,1337.0000,18564.0,0.0,4P4,111999.0,220101.0,585.63,2020-01-27 00:00:00.000000000,2020-01-27 00:00:00.000000000,13.0,ONL,0
24947,EUR,1337.0000,18499.0,0.0,4P4,111999.0,220101.0,333.25,2020-01-27 00:00:00.000000000,2020-01-27 00:00:00.000000000,14.0,ONL,0
24948,EUR,1337.0000,18478.0,0.0,4P4,111999.0,220105.0,55838.90,2020-01-27 00:00:00.000000000,2020-01-27 00:00:00.000000000,15.0,ONL,0

End date: 26/10/2020
Start Date: 07/07/2020

In [ ]:
start = "1970-01-01"
end = "2020-01-27"
days = np.busday_count(start, end)
print(f"The total number of business days are {days}")

The total number of business days are 13062